### ISSUE TITLE
not issue, please help: how you convert your ssd_inception_v2_coco frozen model to movidius

### ISSUE THREAD

**Issue by ucolchen** [madarp/jimmyjohn#1]
Hi, there,
i tried to compile frozen model to graph file for movidius throu. this command:

mvNCCompile -s 12 frozen_inference_graph.pb -in=image_tensor -on=Postprocessor/Reshape_1

but got this error:

mvNCCompile v02.00, Copyright @ Movidius Ltd 2016

/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.4 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.5
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: builtins.type size changed, may indicate binary incompatibility. Expected 432, got 412
  return f(*args, **kwds)
/home/pi/.local/lib/python3.5/site-packages/tensorflow/python/util/tf_inspect.py:75: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  return _inspect.getargspec(target)
Traceback (most recent call last):
  File "/usr/local/bin/mvNCCompile", line 118, in <module>
    create_graph(args.network, args.inputnode, args.outputnode, args.outfile, args.nshaves, args.inputsize, args.weights)
  File "/usr/local/bin/mvNCCompile", line 104, in create_graph
    net = parse_tensor(args, myriad_config)
  File "/usr/local/bin/ncsdk/Controllers/TensorFlowParser.py", line 259, in parse_tensor
    input_data = np.random.uniform(0, 1, shape)
  File "mtrand.pyx", line 1306, in mtrand.RandomState.uniform
  File "mtrand.pyx", line 242, in mtrand.cont2_array_sc
TypeError: 'NoneType' object cannot be interpreted as an integer

please guild how you converted the trained result model  to movidius.
thanks,
q

**Comment by madarp** [comment]
Greetings Q,
Thanks for your inquiry.  I regret to say that I've stopped work on this
particular repo about a year ago after changing jobs.  However, this
particular error was giving me problems just like you.  How to convert the
TF trained model to run on Movidius?  It is not as simple as using
mvncCompile, and I was pursuing the answer to this on the Movidius user
forums:
https://ncsforum.movidius.com/discussion/339/is-there-a-tutorial-or-documentation-for-running-custom-tensorflow-network-in-movidius#latest
I am sorry to say that I did not complete this work, and the repository has
gone stale as I have focused on other projects.  If you find the correct
way to do this I invite you to reply again.
Regards,
P Madar

**Comment by ucolchen** [comment]
thank you P, i will keep eyes on this thread and keep you sync if i got update,
best,
q
